# Generated by Django 6.0.2 on 2026-05-05 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.CharField(max_length=50)),
                ('model_version', models.CharField(max_length=20)),
                ('inference_type', models.CharField(choices=[('RA', 'Risk Analysis'), ('AD', 'Anomaly Detection'), ('RL', 'Risk Labeling')], max_length=2)),
                ('inference_result_raw', models.JSONField(blank=True, null=True)),
                ('parameter_for_inference', models.CharField(choices=[('BP', 'BLood Pressure'), ('BS', 'Blood Sugar')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='ai_engine_i_user_id_4f4880_idx'), models.Index(fields=['inference_type'], name='ai_engine_i_inferen_952cf4_idx')],
            },
        ),
    ]
