# Generated by Django 6.0.2 on 2026-02-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], max_length=20),
        ),
    ]
