# Generated by Django 6.0.2 on 2026-02-20 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HelthProfile',
            new_name='HealthProfile',
        ),
        migrations.RenameField(
            model_name='bloodsugar',
            old_name='Blood_sugar_reading',
            new_name='blood_sugar_reading',
        ),
        migrations.RenameField(
            model_name='healthprofile',
            old_name='height_in_meters',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='healthprofile',
            old_name='is_disable',
            new_name='is_disabled',
        ),
        migrations.AddField(
            model_name='exerciseduration',
            name='type',
            field=models.CharField(choices=[('C', 'Cardio'), ('S', 'Strength Training'), ('F', 'Flexibility Exercises')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
