# Generated by Django 6.0.2 on 2026-02-20 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_data_manager', '0002_rename_helthprofile_healthprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthprofile',
            old_name='height',
            new_name='height_in_meters',
        ),
    ]
