# Generated by Django 6.0.2 on 2026-04-11 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data_manager', '0004_alter_bloodsugar_timestamp_alter_bp_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weight',
            old_name='weight',
            new_name='weight_in_kg',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='unit',
        ),
        migrations.AlterField(
            model_name='bloodsugar',
            name='blood_sugar_reading',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='pulse',
            name='pulse_reading',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
