# Generated by Django 6.0.2 on 2026-04-15 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_data_manager', '0005_rename_weight_weight_weight_in_kg_remove_weight_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodsugar',
            old_name='blood_sugar_reading',
            new_name='blood_sugar_reading_mgdl',
        ),
        migrations.RemoveField(
            model_name='bloodsugar',
            name='unit',
        ),
    ]
