# Generated by Django 6.0.2 on 2026-04-15 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_data_manager', '0006_rename_blood_sugar_reading_bloodsugar_blood_sugar_reading_mgdl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperature',
            old_name='temperature_reading',
            new_name='temperature_reading_celsius',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='unit',
        ),
    ]
