# Generated by Django 6.0.2 on 2026-04-15 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data_manager', '0007_rename_temperature_reading_temperature_temperature_reading_celsius_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleeptime',
            name='sleep_duration',
        ),
        migrations.RemoveField(
            model_name='sleeptime',
            name='unit',
        ),
        migrations.AddField(
            model_name='sleeptime',
            name='sleep_duration_hours',
            field=models.FloatField(default=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(16.0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exerciseduration',
            name='exercise_duration',
            field=models.FloatField(),
        ),
    ]
