# Generated by Django 6.0.2 on 2026-05-05 05:03

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data_manager', '0008_remove_sleeptime_sleep_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodsugar',
            options={'verbose_name_plural': 'Blood Sugar Readings'},
        ),
        migrations.AlterModelOptions(
            name='bp',
            options={'verbose_name': 'Blood Pressure', 'verbose_name_plural': 'Blood Pressures'},
        ),
        migrations.AlterModelOptions(
            name='disability',
            options={'verbose_name_plural': 'Disabilities'},
        ),
        migrations.AlterModelOptions(
            name='exerciseduration',
            options={'verbose_name': 'Exercise', 'verbose_name_plural': 'Exercises'},
        ),
        migrations.AlterModelOptions(
            name='healthprofile',
            options={'verbose_name_plural': 'Health Profiles'},
        ),
        migrations.AlterModelOptions(
            name='pulse',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='sleeptime',
            options={'verbose_name': 'Sleep Time', 'verbose_name_plural': 'Sleep Times'},
        ),
        migrations.AlterModelOptions(
            name='stresslevel',
            options={'verbose_name': 'Stress Level', 'verbose_name_plural': 'Stress Levels'},
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='weight',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='bloodsugar',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bp',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='disability',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exerciseduration',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pulse',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sleeptime',
            name='sleep_duration_hours',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(14.0)]),
        ),
        migrations.AlterField(
            model_name='sleeptime',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stresslevel',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='weight',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='pulse',
            index=models.Index(fields=['user', '-timestamp'], name='health_data_user_id_1d5688_idx'),
        ),
        migrations.AddIndex(
            model_name='pulse',
            index=models.Index(fields=['is_deleted', '-timestamp'], name='health_data_is_dele_be7abe_idx'),
        ),
        migrations.AddIndex(
            model_name='temperature',
            index=models.Index(fields=['user', '-timestamp'], name='health_data_user_id_322792_idx'),
        ),
        migrations.AddIndex(
            model_name='temperature',
            index=models.Index(fields=['is_deleted', '-timestamp'], name='health_data_is_dele_ef30c7_idx'),
        ),
        migrations.AddIndex(
            model_name='weight',
            index=models.Index(fields=['user', '-timestamp'], name='health_data_user_id_5c8ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='weight',
            index=models.Index(fields=['is_deleted', '-timestamp'], name='health_data_is_dele_7105a0_idx'),
        ),
    ]
