# Generated by Django 6.0.5 on 2026-05-08 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_data_manager', '0009_alter_bloodsugar_options_alter_bp_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseduration',
            old_name='exercise_duration',
            new_name='exercise_duration_in_minutes',
        ),
        migrations.RemoveField(
            model_name='exerciseduration',
            name='unit',
        ),
    ]
