# Generated by Django 6.0.5 on 2026-05-08 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data_manager', '0010_rename_exercise_duration_exerciseduration_exercise_duration_in_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseduration',
            name='exercise_duration_in_minutes',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(200.0)]),
        ),
    ]
