# Generated by Django 6.0.2 on 2026-04-17 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Informational'), ('MEDIUM', 'Normal'), ('HIGH', 'Important'), ('CRITICAL', 'Warning')], default='LOW', max_length=10)),
                ('channel', models.CharField(choices=[('APP', 'Notification_page'), ('EMAIL', 'Email'), ('ALL', 'All_channels')], default='APP', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_776dd3_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_ce6926_idx'), models.Index(fields=['priority', '-created_at'], name='notificatio_priorit_6295c6_idx')],
            },
        ),
    ]
